[tool.poetry]
name = "survey"
version = "0.1.0"
description = ""
authors = ["kowaliks <kowal96@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
PyDrive2 = "^1.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
